<?php

namespace TNTMOCO\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfFileRepository extends EntityRepository
{
	public function getFiles($user, $usersIds, $file, $limit){
		
		$qb = $this->createQueryBuilder('f');		
		
		$qb->where(
			$qb->expr()->orX(
				$qb->expr()->eq('f.isLocked', '0'),
				$qb->expr()->eq('f.openedBy', $user)
			)
		)
		->andWhere('f.isRejected = 0')
		->andWhere('f.isCompleted = 0')
		->orderBy('f.id')
		->setMaxResults($limit);
		
		if(count($usersIds) > 0){
			$qb->andWhere(
				$qb->expr()->in('f.user', $usersIds)
			);
		}
		
		if(null !== $file){
			$qb->andWhere('f.id > :fileId')->setParameter('fileId', $file->getId()); 
		}
		
		
		
		return $qb->getQuery()->getResult();
	}
	
}
