TNTMOCO\AppBundle\Entity\User:
    exclusion_policy: none 
    properties:
        password:
            exclude: true
        role:
            exclude: true
        salt:
            exclude: true
        countries:
            exclude: true
            