
home:
    path:     /home
    defaults: { _controller: TNTMOCOAppBundle:Backend\Default:index }

login:
    path:     /login
    defaults: { _controller: TNTMOCOAppBundle:Backend\Security:login }
    
login_check:
    path: /login_check 

logout:
    path: /logout
    
recovery:
    path:     /recovery/{code}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Security:recovery, code:false }
    
    
    
countries:
    path:     /countries
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:index }
    
entity_method:
    path:     /entity/{entityName}/{entityId}/{entityMethod}/{value}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Global:entityMethod }    

countries_assign:
    path:     /countries/assign
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:assign }

countries_assign_users:
    path:     /countries/assign/users
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:usersAssign }

users:
    path:     /users
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:index }

users_edit:
    path:     /users/edit/{userId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:edit }
    
user_profile_edit:
    path:     /profile/edit
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:editProfile }
   

users_create:
    path:     /users/create
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:create }   
    
depots:
    path:     /depots
    defaults: { _controller: TNTMOCOAppBundle:Backend\Depots:index }
    
depots:
   path:     /depots
   defaults: { _controller: TNTMOCOAppBundle:Backend\Depots:index }
   
users_depots:
   path:     /users/depots
   defaults: { _controller: TNTMOCOAppBundle:Backend\Users:depots }

    
test_files:
    path: /test/files
    defaults: { _controller: TNTMOCOAppBundle:Backend\Test:files }
    
display_files:
    path: /files/display/{batchCode}/{fileId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Files:display }
    
    
