
home:
    path:     /home
    defaults: { _controller: TNTMOCOAppBundle:Backend\Default:index }

login:
    path:     /login
    defaults: { _controller: TNTMOCOAppBundle:Backend\Security:login }
    
login_check:
    path: /login_check 

logout:
    path: /logout
    
password_recovery:
    path:     /recovery/{code}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Security:passwordRecovery, code:false }
    
password_generation:
    path:     /password/generation
    defaults: { _controller: TNTMOCOAppBundle:Backend\Security:passwordGeneration }
    
countries:
    path:     /countries
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:index }
    
entity_method:
    path:     /entity/{entityName}/{entityId}/{entityMethod}/{value}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Global:entityMethod }    

countries_assign:
    path:     /countries/assign
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:assign }

countries_assign_users:
    path:     /countries/assign/users
    defaults: { _controller: TNTMOCOAppBundle:Backend\Countries:usersAssign }

users:
    path:     /users
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:index }

users_edit:
    path:     /users/edit/{userId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:edit }
    
user_profile_edit:
    path:     /profile/edit
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:editProfile }
   
users_create:
    path:     /users/create
    defaults: { _controller: TNTMOCOAppBundle:Backend\Users:create }   
    
depots:
    path:     /depots
    defaults: { _controller: TNTMOCOAppBundle:Backend\Depots:index }
    
depots:
   path:     /depots
   defaults: { _controller: TNTMOCOAppBundle:Backend\Depots:index }
   
users_depots:
   path:     /users/depots
   defaults: { _controller: TNTMOCOAppBundle:Backend\Users:depots }
    
test_files:
    path: /test/files
    defaults: { _controller: TNTMOCOAppBundle:Backend\Test:files }
    
display_files:
    path: /files/display/{batchCode}/{fileId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\Files:display }
    
data_entry:
    path: /dataEntry
    defaults: { _controller: TNTMOCOAppBundle:Backend\DataEntry:index }
    
data_entry_country:
    path: /dataEntry/countries/{countryId}/{roleId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\DataEntry:country, roleId:0 }     

data_entry_depot:
    #path: /dataEntry/depots/{depotId}/{fileId}/{prevFileId}/{reject}/{complete}
    path: /dataEntry/depots/{depotId}
    defaults: { _controller: TNTMOCOAppBundle:Backend\DataEntry:depot, fileId:0, prevFileId:0, reject:false, complete:false}
    
reports:
    path:     /reports
    defaults: { _controller: TNTMOCOAppBundle:Backend\Reports:index }
    
