parameters:
#    tntmoco_app.example.class: TNTMOCO\AppBundle\Example

services:
#    tntmoco_app.example:
#        class: %tntmoco_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tntmoco_security.authentication_failure_event_listener:
        class: TNTMOCO\AppBundle\EventListener\AuthenticationFailureListener
        arguments:
            entity_manager: @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_subscriber }
